temporarily setup elis branch

diff --git a/.github/workflows/lsst-tests.yml b/.github/workflows/lsst-tests.yml
--- a/.github/workflows/lsst-tests.yml
+++ b/.github/workflows/lsst-tests.yml
@@ -44,6 +44,22 @@ jobs:
 
           python -m pip install -e .
 
+          git clone --branch u/erykoff/onlinecoadd https://github.com/lsst/pipe_tasks.git /tmp/pipe_tasks
+
+      - name: temporarily use branch
+        shell: bash -l {0}
+        run: |
+            env
+
+            setup -j -r /tmp/pipe_tasks
+
+            pushd /tmp/pipe_tasks
+            # this might partly fail but that's ok
+            scons || echo "ok scons fails"
+            popd
+
+            pip install --no-deps -e .
+
       - name: test ngmix w/ conda latest
         shell: bash -l {0}
         run: |
